name: win_diggy
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.18+18

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_cupertino_localizations: ^1.0.1
  countdown: ^0.1.0
  soundpool: ^0.5.3
  rect_getter: 0.0.1
  firebase_messaging: 6.0.1
  http: ^0.12.0+1
  intl: ^0.16.0
  shared_preferences: ^0.5.4+5
  firebase_auth: ^0.14.0
  modal_progress_hud: ^0.1.2
  image_picker: ^0.6.1+4
  country_pickers: ^1.1.0
  country_code_picker: ^1.1.7
  flutter_local_notifications: ^0.8.4
  percent_indicator: ^2.1.1
  screenshot: ^0.1.1
  pin_entry_text_field: ^0.1.3
  firebase_database: ^3.1.0
  cached_network_image: ^2.0.0-rc.1
  flutter_swiper: ^1.1.6
  flutter_cache_manager: ^1.1.3
  flutter_i18n: ^0.8.2
  pin_code_text_field: ^1.5.0
  flutter_advanced_networkimage: ^0.6.0-alpha.1
  url_launcher: ^5.2.7
  package_info: ^0.4.0+11
  firebase_remote_config: ^0.2.1
  badges: ^1.1.0
  auto_direction: ^0.0.4+1
  intl_phone_number_input: ^0.1.3
  cupertino_icons: ^0.1.2
  share: ^0.6.3+5
  ntp: ^1.0.5
  facebook_sdk: ^0.0.7
  sqflite: ^1.2.0
  path_provider: ^1.5.1
  flutter_image_compress: ^0.6.5
  firebase_crashlytics: ^0.1.2+4
  connectivity: ^0.4.6+2
  provider: ^2.0.1
  flutter_linkify: ^3.1.0
  animator: ^1.0.0+3
  video_player:
  chewie:
  flutter_staggered_grid_view: ^0.3.0
  progress_dialog: ^1.2.1
  trust_fall: ^1.0.4
  wakelock: ^0.1.3+4
  network_image_to_byte: ^0.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
      - assets/defaultImg.png
      - assets/cancel.svg
      - assets/cup.svg
      - assets/circle_outline.svg
      - assets/alarm_clock.svg
      - assets/smartphone.svg
      - assets/contactus.svg
      - assets/OTP_ver.svg
      - assets/instagram.svg
      - assets/linkedin.svg
      - assets/facebook.svg
      - assets/twitter.svg
      - assets/Clock.png
      - assets/grow.png
      - assets/Race.png
      - assets/road.png
      - assets/glitters.gif
      - assets/ur.json
      - assets/en.json
      - assets/logo.png
      - assets/instant-reward.png
      - assets/logo_text.png
      - assets/banner.jpg
      - assets/bannerAd.jpg
      - assets/add.mp3
      - assets/pop.mp3
      - assets/flip.mp3
      - assets/flipMatch.mp3
      - assets/game.svg
      - assets/cup2.svg
      - assets/1
      - assets/tissuePaper
      - assets/bonus.png
      - assets/star.svg
      - assets/rank.svg





  fonts:
      - family: PuzzleIcons
        fonts:
            - asset: fonts/PuzzleIcons.ttf
      - family: Pacifico
        fonts:
            - asset: fonts/Pacifico-Regular.ttf
      - family: Source Sans
        fonts:
            - asset: fonts/SourceSansPro-SemiBold.ttf
      - family: Lilita One
        fonts:
            - asset: fonts/LilitaOne-Regular.ttf
      - family: Coustard
        fonts:
            - asset: fonts/Coustard-Black.ttf
      - family: Baloo
        fonts:
            - asset: fonts/Baloo-Regular.ttf
      - family: Comfortaa
        fonts:
            - asset: fonts/Comfortaa-VariableFont_wght.ttf
      - family: Yeon
        fonts:
            - asset: fonts/YeonSung-Regular.ttf
      - family: BreeSerif
        fonts:
            - asset: fonts/BreeSerif-Regular.ttf
      - family: PatuaOne
        fonts:
            - asset: fonts/PatuaOne-Regular.ttf
      - family: Lato
        fonts:
            - asset: fonts/Lato-Bold.ttf
      - family: Yrsa
        fonts:
            - asset: fonts/Yrsa-Regular.ttf
      - family: Shojumaru
        fonts:
            - asset: fonts/Shojumaru-Regular.ttf
      - family: Belgrano
        fonts:
            - asset: fonts/Belgrano-Regular.ttf
      - family: Rokkitt
        fonts:
            - asset: fonts/Rokkitt-VariableFont_wght.ttf
      - family: Signika Semibold
        fonts:
            - asset: fonts/Signika-SemiBold.ttf
      - family: Signika Light
        fonts:
            - asset: fonts/Signika-Light.ttf
      - family: Futura
        fonts:
            - asset: fonts/Futura-medium-bt.ttf
      - family: Noteworthy
        fonts:
            - asset: fonts/Noteworthy-Lt.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
