/// Flutter icons PuzzleIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PuzzleIcons
///      fonts:
///       - asset: fonts/PuzzleIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class PuzzleIcons {
  PuzzleIcons._();

  static const _kFontFam = 'PuzzleIcons';
  static const _kFontPkg = null;

  static const IconData signal_wifi_off = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm_clock = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData live_chat = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up_hand_symbol = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cup = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData score = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scoreboard = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
